typography_spectrum: 0.6014259294606745
color:
  brandColors:
    - '#291715'
    - '#bca15e'
    - '#7c674a'
    - '#978056'
    - '#e6d086'
  brandStrength: 0.9405985774938017
  lightness: 0.13900405704043806
  saturation: 0.290127772372216
  rhythmicContrast: 0.8181266288738698
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8897155181039125
analytics:
  google: null
  facebook: null
  twitter: null
name: edgehog
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: on the eDGe
purpose: []
